### PR TITLE
Avoid add M exec-opt twice

### PR DESCRIPTION
**Pull request by bootleq**
Hi, when using `iced repl` command,
sometimes I need to use different aliases with clj `-M` exec option,
for example `iced repl -M:xx:yy:iced`,
but it produces another `-M` in `MAIN_FLAG` handling and makes the prior no-effect.

This PR try to detect `-M` in command line options and avoid second `-M` as an fix.

### CODE REVIEW

**Review by liquidz — CHANGES_REQUESTED** [review]
@bootleq Thanks for your contribution!
Looks good to me, but just sorry, could you fix the following file instead of `bin/iced` ?
https://github.com/liquidz/vim-iced/blob/ed226c734c020694d74f04de934fa9be0a34cf81/clj/template/iced.bash#L404-L408

`bin/iced` is generated by this template file via `make bin` command.
It may be good to add notes about this to the head of template file.

**Comment by bootleq** [comment]
Hi, thanks for the reminder, I have changed the template, too.

Feel uncertain to add note to template, because someone didn't notice the file like me, will also overlook the note.

**Comment by liquidz** [comment]
@bootleq Thank you!

> Feel uncertain to add note to template, because someone didn't notice the file like me, will also overlook the note.

If we add notes to the template and run `make bin`, bin/iced will also have same notes.

So it should help to avoid overlooking.

**Comment by bootleq** [comment]
> If we add notes to the template and run `make bin`, bin/iced will also have same notes.
> 
> So it should help to avoid overlooking.

Understand, how about this comment?

    # This file is generated by `make bin`.

**Comment by liquidz** [comment]
It might be helpful to specify what action to take if someone want to make a change.
e.g.
```
# === WARNING ===
# bin/iced is generated by `make bin`.
# Please edit clj/template/iced.bash instead of bin/iced.
```

**Comment by bootleq** [comment]
Thanks, I have added the comment, hope further contributors will find those files were changed together.

**Review by liquidz — APPROVED** [review]
@bootleq Thank you so much! LGTM

**Pull request merged**
